// flow-typed signature: 0fd155389661115c0aeaddfa71b56acc
// flow-typed version: <<STUB>>/lazy-promise_v^4.0.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lazy-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lazy-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lazy-promise/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lazy-promise/lib/index.js' {
  declare module.exports: $Exports<'lazy-promise/lib/index'>;
}
