// flow-typed signature: bc76e75f44fbb13dc4527a9c0d8bb34c
// flow-typed version: <<STUB>>/mocha.parallel_v^0.15.6/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha.parallel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha.parallel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mocha.parallel/lib/contextProxy' {
  declare module.exports: any;
}

declare module 'mocha.parallel/lib/parallel' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/assertionFailure' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/contextProxy' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/contextSkip' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/contextTimeout' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/defaultTimeout' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/delay' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/disable' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/failure' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/foobar' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/hooks' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/hooksExample' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/limit' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/multiple' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/only' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/parallelOnly' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/parallelSkip' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/parentHooks' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/promiseRejection' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/rootHooks' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/skip' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/sync' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/syncTime' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/fixtures/uncaughtException' {
  declare module.exports: any;
}

declare module 'mocha.parallel/spec/spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mocha.parallel/lib/contextProxy.js' {
  declare module.exports: $Exports<'mocha.parallel/lib/contextProxy'>;
}
declare module 'mocha.parallel/lib/parallel.js' {
  declare module.exports: $Exports<'mocha.parallel/lib/parallel'>;
}
declare module 'mocha.parallel/spec/fixtures/assertionFailure.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/assertionFailure'>;
}
declare module 'mocha.parallel/spec/fixtures/contextProxy.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/contextProxy'>;
}
declare module 'mocha.parallel/spec/fixtures/contextSkip.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/contextSkip'>;
}
declare module 'mocha.parallel/spec/fixtures/contextTimeout.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/contextTimeout'>;
}
declare module 'mocha.parallel/spec/fixtures/defaultTimeout.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/defaultTimeout'>;
}
declare module 'mocha.parallel/spec/fixtures/delay.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/delay'>;
}
declare module 'mocha.parallel/spec/fixtures/disable.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/disable'>;
}
declare module 'mocha.parallel/spec/fixtures/failure.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/failure'>;
}
declare module 'mocha.parallel/spec/fixtures/foobar.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/foobar'>;
}
declare module 'mocha.parallel/spec/fixtures/hooks.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/hooks'>;
}
declare module 'mocha.parallel/spec/fixtures/hooksExample.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/hooksExample'>;
}
declare module 'mocha.parallel/spec/fixtures/limit.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/limit'>;
}
declare module 'mocha.parallel/spec/fixtures/multiple.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/multiple'>;
}
declare module 'mocha.parallel/spec/fixtures/only.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/only'>;
}
declare module 'mocha.parallel/spec/fixtures/parallelOnly.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/parallelOnly'>;
}
declare module 'mocha.parallel/spec/fixtures/parallelSkip.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/parallelSkip'>;
}
declare module 'mocha.parallel/spec/fixtures/parentHooks.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/parentHooks'>;
}
declare module 'mocha.parallel/spec/fixtures/promiseRejection.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/promiseRejection'>;
}
declare module 'mocha.parallel/spec/fixtures/rootHooks.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/rootHooks'>;
}
declare module 'mocha.parallel/spec/fixtures/skip.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/skip'>;
}
declare module 'mocha.parallel/spec/fixtures/sync.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/sync'>;
}
declare module 'mocha.parallel/spec/fixtures/syncTime.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/syncTime'>;
}
declare module 'mocha.parallel/spec/fixtures/uncaughtException.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/fixtures/uncaughtException'>;
}
declare module 'mocha.parallel/spec/spec.js' {
  declare module.exports: $Exports<'mocha.parallel/spec/spec'>;
}
