// flow-typed signature: 8be1f83e1a8dd680ded2bf8bdf60bbd7
// flow-typed version: <<STUB>>/parallel-transform-stream_v^1.0.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parallel-transform-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parallel-transform-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parallel-transform-stream/dist/parallel-transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parallel-transform-stream/dist/parallel-transform.js' {
  declare module.exports: $Exports<'parallel-transform-stream/dist/parallel-transform'>;
}
