// flow-typed signature: ece70c753f91d78c40042be5783416d4
// flow-typed version: <<STUB>>/pump_v^3.0.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pump'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pump' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pump/test-browser' {
  declare module.exports: any;
}

declare module 'pump/test-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pump/index' {
  declare module.exports: $Exports<'pump'>;
}
declare module 'pump/index.js' {
  declare module.exports: $Exports<'pump'>;
}
declare module 'pump/test-browser.js' {
  declare module.exports: $Exports<'pump/test-browser'>;
}
declare module 'pump/test-node.js' {
  declare module.exports: $Exports<'pump/test-node'>;
}
