// flow-typed signature: 4daf040aa97d3efdb62c5327056d9b2f
// flow-typed version: <<STUB>>/split2_v^3.0.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'split2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'split2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'split2/bench' {
  declare module.exports: any;
}

declare module 'split2/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'split2/bench.js' {
  declare module.exports: $Exports<'split2/bench'>;
}
declare module 'split2/index' {
  declare module.exports: $Exports<'split2'>;
}
declare module 'split2/index.js' {
  declare module.exports: $Exports<'split2'>;
}
declare module 'split2/test.js' {
  declare module.exports: $Exports<'split2/test'>;
}
