// flow-typed signature: 054caba36d3cf99a2ac063ee037ea2fc
// flow-typed version: <<STUB>>/stream-array_v^1.1.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stream-array'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stream-array' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stream-array/test/1' {
  declare module.exports: any;
}

declare module 'stream-array/test/2' {
  declare module.exports: any;
}

declare module 'stream-array/test/3' {
  declare module.exports: any;
}

declare module 'stream-array/test/4' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stream-array/index' {
  declare module.exports: $Exports<'stream-array'>;
}
declare module 'stream-array/index.js' {
  declare module.exports: $Exports<'stream-array'>;
}
declare module 'stream-array/test/1.js' {
  declare module.exports: $Exports<'stream-array/test/1'>;
}
declare module 'stream-array/test/2.js' {
  declare module.exports: $Exports<'stream-array/test/2'>;
}
declare module 'stream-array/test/3.js' {
  declare module.exports: $Exports<'stream-array/test/3'>;
}
declare module 'stream-array/test/4.js' {
  declare module.exports: $Exports<'stream-array/test/4'>;
}
